### ISSUE TITLE
ERA5 authentification/ tuple not callable error

### ISSUE THREAD

**Issue by MartinSJRogers** [icenet-ai/icenet-pipeline#7]
The error below is derived when trying to download ERA5 data. It is likely this is due to the authentification key used, but would be worth checking to ensure others don't encounter this hurdle. A subset of the error code is found below, but a similar error code is derived for all the ERA5 datasets that I tried to download. 

INFO:root:ERA5 Data Downloading
INFO:root:Building request(s), downloading and daily averaging from ERA5 API
INFO:root:Downloading data for ta500...
ERROR:root:./data/era5/south/ta500/2019/download_ta500_12_2019.nc not deleted, look at the problem
Traceback (most recent call last):
  File "/data/hpcdata/users/marrog/icenet/icenet2/data/interfaces/cds.py", line 258, in _single_api_download
    self.client.retrieve(dataset, retrieve_dict, temp_download_path)
  File "/data/hpcdata/users/marrog/conda-env/icenet-pipeline/lib/python3.8/site-packages/cdsapi/api.py", line 348, in retrieve
    result = self._api("%s/resources/%s" % (self.url, name), request, "POST")
  File "/data/hpcdata/users/marrog/conda-env/icenet-pipeline/lib/python3.8/site-packages/cdsapi/api.py", line 417, in _api
    result = self.robust(action)(
  File "/data/hpcdata/users/marrog/conda-env/icenet-pipeline/lib/python3.8/site-packages/cdsapi/api.py", line 606, in wrapped
    r = call(*args, **kwargs)
  File "/data/hpcdata/users/marrog/conda-env/icenet-pipeline/lib/python3.8/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/data/hpcdata/users/marrog/conda-env/icenet-pipeline/lib/python3.8/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/data/hpcdata/users/marrog/conda-env/icenet-pipeline/lib/python3.8/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/data/hpcdata/users/marrog/conda-env/icenet-pipeline/lib/python3.8/site-packages/requests/models.py", line 372, in prepare
    self.prepare_auth(auth, url)
  File "/data/hpcdata/users/marrog/conda-env/icenet-pipeline/lib/python3.8/site-packages/requests/models.py", line 603, in prepare_auth
    r = auth(self)
TypeError: 'tuple' object is not callable
INFO:root:Downloading data for tos...
ERROR:root:Thread failure: 'tuple' object is not callable

**Comment by JimCircadian** [comment]
Hi @MartinSJRogers 

I believe you resolved this issue, can you confirm? 

The format of the auth credentials for CDS API are probably wrong, they should look like this: 

```
cat ~/.cdsapirc 
url: https://cds.climate.copernicus.eu/api/v2
key: nnnnn:<<keyRedacted>>
```

**Comment by MartinSJRogers** [comment]
@JimCircadian yes all sorted- I will close the issue.
